name: panvimdoc

on:
  push:
    branches: [master]
    paths:
      - README.md 
      - .github/workflows/doc.yml 

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "NVIM v0.10.2+"
          toc: true 
          dedupsubheadings: true 
          treesitter: true 
          docmapping: true 
          docmappingprojectname: true 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build):Auto generate docs"
          branch: ${{ github.head_ref }}
