name: Create Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "readme.md"
          body_path: "readme.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

